### ISSUE TITLE
Force in-character for players only

### ISSUE THREAD

**Issue by HumanWreck** [cs96and/FoundryVTT-CGMP#10]
First, I would like to thank you for all your hard work. This is very helpful module. 

Issue:
I know this might be a step back, but I would really appreciate if there would be an option to have "Force in-character" feature available for players, while keeping "Disable GM speak as PC" for GMs. 

This is very interesting feature for groups playing without V/C, since you wouldn´t have to place PC tokens on every scenery scene to enable players to speak in-character without the necessity of using /ic command for every message. On the other hand, GM still wants to avoid speaking as PC, because it happens all the time that GM forgets to unselect PC token after checking out some character details. 

The other option would be implementing a feature where every player can set a default prefix for all his non-roll messages. Use cases:
/ic for players.
/desc for GMs.

**Comment by cs96and** [comment]
db4396cc09393559ce6935220882c4bef10ffbc3

**Comment by cs96and** [comment]
Fixed in 0.6.  There are now separate GM and player speaker modes.

**Comment by HumanWreck** [comment]
Amazing Sir, thank you very much.
