### ISSUE TITLE
"Disable GM Speaking" applies to Pathfinder 1 attacks

### ISSUE THREAD

**Issue by DrMcCoy** [cs96and/FoundryVTT-CGMP#12]
In [the Pathfinder 1 system](https://foundryvtt.com/packages/pf1), "Disable GM speaking as PC" also disables the GM rolling attacks and casting spells as the player character.

Rolling saves, attributes, etc. works, but everything that's more complicated than a simple roll counts as speaking as far as this module is concerned.

**Comment by cs96and** [comment]
ffed9c8bc80b0f2c86f7587dc18c832c6deb70e9

**Comment by cs96and** [comment]
Fixed in 0.7.1.  Sorry for the delay.
