### ISSUE TITLE
CGMP overwrites color of /emote text

### ISSUE THREAD

**Issue by azc001** [cs96and/FoundryVTT-CGMP#14]
CGMP forces the text color of /emote to be dark grey, making it incompatible with modules such as Chat Colors & More or D&D 5e Dark Mode as the modules are unable to change the text color of /emote from this dark grey color.

**Chat Colors & More:**
![With CGMP](https://i.imgur.com/zOAluyy.png)  
Without CGMP

![With CGMP](https://i.imgur.com/FlauqOv.png)  
With CGMP

---

**D&D 5e Dark Mode:**
![With CGMP](https://i.imgur.com/9SiHS3l.png)  
Without CGMP

![With CGMP](https://i.imgur.com/Pm5HlFQ.png)  
With CGMP

**Comment by cs96and** [comment]
I feel like the correct place to fix this is in the other modules.  They should be able override the emote text colour with an `!important` css tag.
