### ISSUE TITLE
deprecated items

### ISSUE THREAD

**Issue by HippyCraig** [cs96and/FoundryVTT-CGMP#15]
I updated to v286 and see the following

![image](https://user-images.githubusercontent.com/17074456/192174667-937712f1-96a1-4430-8303-3f5dbfdd714e.png)

**Comment by cs96and** [comment]
This is not a major issue.  Although deprecated, it will be supported until v13.
https://foundryvtt.com/article/manifest-migration-guide/

I will change it at some point, but it's not top of my todo list at the moment.

**Comment by HippyCraig** [comment]
Thanks

**Comment by cs96and** [comment]
15c25cc7a56cd2ba725a034ad9f728d55abe4027

**Comment by cs96and** [comment]
Fixed in v0.9.1

**Comment by HippyCraig** [comment]
looks good
Sorry I was on vacation thats why i didnt respnond sooner
