### ISSUE TITLE
[Feature Request] More Player Speaker Modes

### ISSUE THREAD

**Issue by airbreather** [cs96and/FoundryVTT-CGMP#19]
# Problem

We have a big travel map where each party member has control over a token that's just called "The Party".  I'm able to work around the obvious issue of everyone's chat coming in as if it's from "The Party" by putting everybody's token into a walled-off box somewhere off to the side, but that doesn't help if someone happens to still have "The Party" selected when they type into the chat box.

# Proposed Solution 1

Can we have a "Player Speaker Mode" that will always speak as a token for the player's assigned character, if one is present on the map, regardless of their selection?

I might submit a PR for this over the next week or so, but I'm logging this just in case you can get to it a bit more quickly.

# Proposed Solution 2

Proposed solution 1 looks easy enough me as a developer, but I'm wearing my "end user requesting an enhancement" hat right now, so, really anything that we could do to make a player no longer automatically "speak as" a token whose actor is controlled by multiple non-GM players.  Maybe a "safer default" mode that wraps `ChatMessage.getSpeaker` to retry without an initial selection if it detects this situation?

**Comment by cs96and** [comment]
Funnily enough I have the exact same problem in my game!  I'll have a think about the best solution to this.

**Comment by cs96and** [comment]
The "Always In Character" speaker mode already solves this problem

**Comment by airbreather** [comment]
The problem I had with using "Always In Character" for this was that players will no longer be able to use `/ooc` to override it for a particular message, right?

I'm not at a computer to confirm this right now...

**Comment by airbreather** [comment]
Anyway, I'll open a PR at some point to elaborate more on the niche that I'm trying to hit with this request, no worries about reopening this issue or anything.  Thanks for what you do!

**Comment by cs96and** [comment]
> The problem I had with using "Always In Character" for this was that players will no longer be able to use `/ooc` to override it for a particular message, right?
> 
> I'm not at a computer to confirm this right now...

Yes that is correct.  I'll see if I can do anything about that.

**Comment by cs96and** [comment]
Available in 1.1.0 (thanks for the PR).
