### ISSUE TITLE
Minor incompatibility with DF chat enhancements

### ISSUE THREAD

**Issue by NdranC** [cs96and/FoundryVTT-CGMP#20]
![image](https://user-images.githubusercontent.com/27837113/215627957-c813c161-8bf2-48e2-928e-f55020a8fda5.png)

Foundry v10.291
DnD 5e v2.1.4

The chat box has unwanted padding underneath.

Not very knowledgeable with css but it seems this is the one causing it
![image](https://user-images.githubusercontent.com/27837113/215628202-9593d224-8226-41c3-ba34-5e6695ffa014.png)
Disabling that seems to fix it but I'm unsure on what it would happen to the typing indicator.

**Comment by cs96and** [comment]
I don't see this issue.  I can see from that screenshot you have several modules enabled.  Please try again with no modules enabled.

**Comment by NdranC** [comment]
Sorry, I though I tested you module with nothing else enabled but now I can see I had another mod locked enabled and I didn't realize. This problem only occurs when using DF chat enhancement in combination with this mod. It seems to be a minor css fix but I'm unsure if this is something you would be willing or able to fix on your end.

Sorry for the miss report and thanks for your time!

**Comment by cs96and** [comment]
I use DF chat enhancements too and do not have this issue.

**Comment by NdranC** [comment]
![image](https://user-images.githubusercontent.com/27837113/216148257-dae28d10-9768-4626-9580-58c82f867bf6.png)

Disabling DF chat enhancements or your module fixes the issue. Is there anything I could do to provide more detailed information?

**Comment by cs96and** [comment]
Is that paper aeroplane part of DF chat enhancements?  It does not appear for me.  Maybe you have some setting turned on that I don't?

**Comment by NdranC** [comment]
I just tested some more and I can confirm that is probably a setting somewhere. I opened my browser in a separate profile instance and loaded foundry and it seems to work fine. I will investigate what setting is causing it and letting you know.

(Yeah the paper airplane is from DF chat enhancements but I deactivated it and didn't fix it)

**Comment by NdranC** [comment]
![image](https://user-images.githubusercontent.com/27837113/216196269-fa7c5687-10c1-49ff-8354-7ea34989af1b.png)

Ok, for some reason I though I tested this setting before and it wasn't the problem but I've must have done it wrong since it's 100% the problem setting. Disabling it fixes the issue.

Just to be clear, this still only happens with your mod and this setting enabled so I guess it still worth pointing out. Let me know if you need anything else.

**Comment by cs96and** [comment]
This is due to the send button trying to set the `float: right` css property, but you can't float things inside a flex container.  CGMP changes the `chat-form` into a flex container so that it can make the typing notification appear and disappear.

I'm not much of a CSS expert, and I don't really know how to fix this, but it appears to me that this would need to be fixed in the DF Chat Enhancements module, not in CGMP.

**Comment by cs96and** [comment]
Given that DF Chat Enhancements is deprecated, I am closing this issue.
