### ISSUE TITLE
[Feature Request] Hidden Initiative for NPCs

### ISSUE THREAD

**Issue by Vaizt** [cs96and/FoundryVTT-CGMP#23]
It seems the module for V9, Hidden Initiative, that did this has become deprecated and will likely not receive a V10 update. This would be a feature that fits very well into the rest of the kit CGMP ships with and I very much like the surprise and suspense of my players not knowing when the NPC combatants will go on the first round.

**Comment by cs96and** [comment]
I believe Monks Little Details will take care of this.
