### ISSUE TITLE
issue with latest release

### ISSUE THREAD

**Issue by zarmstrong** [cs96and/FoundryVTT-CGMP#25]
![image](https://user-images.githubusercontent.com/565269/220997637-4ca64f92-bc9c-4ceb-a722-9d398f76c446.png)

See above

**Comment by cs96and** [comment]
This is an issue with core foundry and github.  Sometimes if you do an "Update All", github starts returning errors as it thinks you are DOS-ing them.  Just try and update CGMP again, and it should work.
