### ISSUE TITLE
Error: on FVTT 11.306

### ISSUE THREAD

**Issue by friction1** [cs96and/FoundryVTT-CGMP#30]
When I tried to update modules today, I got an error below.
<img width="664" alt="Screenshot 2023-07-21 at 8 34 00 AM" src="https://github.com/cs96and/FoundryVTT-CGMP/assets/11384891/981f72d3-8777-46fc-8d8e-6e1cff32a877">

**Comment by cs96and** [comment]
I believe this is a network error, and nothing to do with CGMP.
