### ISSUE TITLE
Use assigned when in-character not working

### ISSUE THREAD

**Issue by LinkedFluuuush** [cs96and/FoundryVTT-CGMP#31]
Hello !

When I set the option 'Use assigned when in-character', every text is sent ooc if I don't specifically add /ic to my message. This kind of defeats the purpose of using the module.
Everything works as expected when using the 'Force in-character' setting, but I want to be able to use /ooc in the chat messages.

FoundryVTT 11.307
CGMP version 1.4.0
System : Custom System Builder 2.4.1

**Comment by cs96and** [comment]
Are you logged in as a player or GM?

**Comment by cs96and** [comment]
Also, does the user have a token on the current scene?  It seems that it works as long as the user has a token on the scene, but it should work regardless of that, so I'll take a look into why that isn't working.

**Comment by LinkedFluuuush** [comment]
I am logged in as a player to test it.

**Comment by LinkedFluuuush** [comment]
Here is my configuration on GM side :
![image](https://github.com/cs96and/FoundryVTT-CGMP/assets/2318106/cfdbc87e-ffb3-4039-94a6-9a22026a8817)

**Comment by cs96and** [comment]
391ef2d7a1573c0a9e196abfcc38159610dd5bd9

**Comment by cs96and** [comment]
Fixed in v1.4.1

**Comment by LinkedFluuuush** [comment]
Perfect, thank you very much !
