### ISSUE TITLE
Weird /desc behavior with Polyglot

### ISSUE THREAD

**Issue by Ghostdesu** [cs96and/FoundryVTT-CGMP#32]
Note: there is a similar issue on the Polyglot page: https://github.com/mclemente/fvtt-module-polyglot/issues/305

Currently it is possible for [Polyglot](https://github.com/mclemente/fvtt-module-polyglot) to scramble CGMP /desc messages. This is inconvenient because selecting a creature that speaks any language other than default switches the language to that creature's, resulting in all /desc messages being scrambled by Polyglot until you manually switch away from it (usually requiring to deselect the creature). 

I believe this could be addressed by changing the /desc message type to other (according to https://github.com/mclemente/fvtt-module-polyglot/issues/305#issuecomment-1728655032 in the aforementioned issue).

**Comment by mclemente** [comment]
I'll add a check on Polyglot to handle this on next release (2.3.2+). Consider this issue fixed.

**Comment by cs96and** [comment]
I was planning to take a look at changing /desc messages to type other, but hadn't got round to it yet.

**Comment by mclemente** [comment]
That makes sense.
I fixed it on my side because there are other modules let users choose the type, so it's easier to just skip messages with the proper flags.

**Comment by cs96and** [comment]
76327fa2d9cfce392c031f52b637f43cf5af924a

**Comment by cs96and** [comment]
Fixed in v1.5.0
