### ISSUE TITLE
Changee to "Hide damage/healing" for NPCs

### ISSUE THREAD

**Issue by TrofimSelbs** [cs96and/FoundryVTT-CGMP#34]
Hey, thank you very much for maintaing this module. I have discovered it today and I am loving it. I have a request that I am fine with not being made into reality, but it would be cool nevertheless. 

I, as a DM, would like to see those scrolling healing/damage numbers. It is really important for me as I want to know how much PC dealt damage at a glance

**Comment by cs96and** [comment]
I seem to recall this wasn't straightforward, but will try to take another look into it.

Given the time of year, I probably won't be able to take a look until the new year though

**Comment by TrofimSelbs** [comment]
thank you very much! no rush

**Comment by cs96and** [comment]
5b98eef9d066fd2acd5f12b3013371dd2a31dd16

**Comment by cs96and** [comment]
Sorry it took nearly a year, but this is now fixed in v1.9.0

**Comment by TrofimSelbs** [comment]
Thanks! That is still very much welcome!
