### ISSUE TITLE
Minor incompatibility with PF2e Dorako UI 

### ISSUE THREAD

**Issue by chaoticnote** [cs96and/FoundryVTT-CGMP#35]
![image](https://github.com/cs96and/FoundryVTT-CGMP/assets/28378016/572527a7-56ca-4942-9837-e77ef90a897f)
![image](https://github.com/cs96and/FoundryVTT-CGMP/assets/28378016/9d540984-ca4e-4bb0-af69-042851e5f77c)

So for whatever reason, when Cautious Gamemaster Pack and PF2e Dorako UI are both enabled, the text style for the **/me** chat message parameter is darkened, thus making it difficult to see for any chat message themes on Dorako that have a dark colored background.

With Cautious Gamemaster Pack disabled, this is how it looks with Dorako UI. Notably, the text is also not centered but instead left-aligned.
![image](https://github.com/cs96and/FoundryVTT-CGMP/assets/28378016/82233e4d-d519-46f3-8dde-84c46299dd0a)

**Comment by grankless** [comment]
Looks like this is still happening - same issues as reported in OP.

**Comment by cs96and** [comment]
3553a7330d7e8e320693e5e4d4feebeea4723bf1

**Comment by cs96and** [comment]
Fixed in v1.8.0
