### ISSUE TITLE
Dynamic Ring Damage/Healing Visual Effects

### ISSUE THREAD

**Issue by maxobremer** [cs96and/FoundryVTT-CGMP#37]
When a token that has a dynamic ring gets damaged or healed, a visible effect is activated. Especially the damage effect can be quit noticeable as the ring colour flickers with red. Would it be possible to have those effects suppressed while the hide scrolling damage/healing text on NPC token option is enabled?

Foundry v12 build 327
dnd5e 3.2.1
CGMP 1.7.0

**Comment by cs96and** [comment]
0fd769d18714185fa31ac5391495ecb83539f126

**Comment by cs96and** [comment]
New option now available in v1.8.0
