### ISSUE TITLE
[Enhancement] Completely hide GM Rolls for hidden tokens

### ISSUE THREAD

**Issue by weepingminotaur** [cs96and/FoundryVTT-CGMP#38]
Would be awesome if a secret roll (for an invisible/hidden token) produced no sound and "GM privately rolled some dice" message in chat. Sometimes (frequently?) you don't even want players to know that you're rolling. :D

**Comment by cs96and** [comment]
There is already another module that does this...
https://foundryvtt.com/packages/actually-private-rolls

Though it doesn't say it is compatible with v12.  It may just work though.

**Comment by cs96and** [comment]
I can confirm that the [Hide GM Rolls](https://foundryvtt.com/packages/hide-gm-rolls) module supports this functionality, and works with v12
