### ISSUE TITLE
Foundry Reported Manifest Error

### ISSUE THREAD

**Issue by Eschguy** [cs96and/FoundryVTT-CGMP#39]
The "Cautious Gamemaster's Pack" module's manifest contained the following unknown keys: "type", "manifestPlusVersion"

**Comment by cs96and** [comment]
I know what the problem is, but I'm not seeing this error anywhere myself.  Where are you seeing this?

**Comment by cs96and** [comment]
e09dabc4603c1f3af3d2aeba01eac81e89235af8

**Comment by cs96and** [comment]
Fixed in v1.9.0
