### ISSUE TITLE
[Compatibility Request] Exclude Chat Portrait avatar from /as messages

### ISSUE THREAD

**Issue by Ghostdesu** [cs96and/FoundryVTT-CGMP#5]
I believe it can be pretty distracting to have an unrelated player avatar next to in-character messages, so I suggest giving /as messages the same treatment as /desc

Example of what /as messages look like right now:
![image](https://user-images.githubusercontent.com/31375910/125283281-f1caf200-e320-11eb-975b-780211c30bd8.png)

What it would ideally look like with this change implemented:
![image](https://user-images.githubusercontent.com/31375910/125283403-11fab100-e321-11eb-96a7-fbf8fecbfcc4.png)

Latest versions of Foundry, dnd5e system, libwrapper, Chat Portrait and CGMP used for testing.

**Comment by cs96and** [comment]
a8d64d3607f6445e0374af4707b89fab6f92b6d3

**Comment by cs96and** [comment]
Fixed in 0.2.7
