### ISSUE TITLE
[Feature Request] Always Speak as GM

### ISSUE THREAD

**Issue by ghost** [cs96and/FoundryVTT-CGMP#7]
Would it be possible to add an option so that GMs never speak as NPCs, they only speak as themselves?

**Comment by cs96and** [comment]
Sounds reasonable.  Thanks for the suggestion

**Comment by cs96and** [comment]
You can sort of achieve this today using the "Force in-character" speaker mode.  If the GM user does not has a character assigned, then they will always speak out-of-character.

However, this does force player to speak in-character all the time (even if they use `/ooc`).

I'm going to add a new speaker mode, similar to "Disable GM speaking as PC", but that forces all the GM's messages to out-of-character.

**Comment by cs96and** [comment]
03a462f11e945199ca099fc8f1fec54b730c72e6
